#!/usr/bin/ruby

require "csv"
require "dotenv/load"
require "sqlite3"
require "time"
require "pathname"

#
# Configuration
#

DATA_PATH = Pathname.new(ENV["DATA_PATH"])
DB_FILENAME = DATA_PATH + ENV["MACHINE_LOAD_DB"]
DATETIME = Time.new().strftime("%Y-%m")
HEADERS = ["DateTime", "Logined Users", "Machine Load"]

#
# Utils function
#

def get_all_machine(db)
  machines = db.execute("SELECT * FROM machine").collect { |row| row }
  return machines
end

def get_data(db, machine_id)
  return(
    db
      .query(
        "SELECT DATETIME(ttime, 'unixepoch') as isodate, users, load FROM record WHERE machine=?",
        machine_id
      )
      .collect { |row| row }
  )
end

#
# Main logic
#

db = SQLite3::Database.open(DB_FILENAME)
machines = get_all_machine(db)

machines.each do |m|
  # m[0] is primary id in database, m[1] is the name alias of the machine
  record = get_data(db, m[0])

  filename = DATA_PATH + "#{m[1]}-#{DATETIME}.csv"
  CSV.open(filename, "w") do |csv|
    csv << HEADERS
    # rec[0] is test datetime, rec[1] is users, rec[2] is load
    record.each do |rec|
      # unmatched have 4 cpu cores
      rec[2] = ((rec[2] / 4) * 100).round(3)
      csv << rec
    end
  end
  puts "#{filename} generated"
end

puts "Process done"
