#!/usr/bin/ruby

# frozen_string_literal: true

require 'dotenv/load'
require 'sqlite3'
require 'time'
require 'pathname'
require 'fileutils'
require 'json'

#
# Configuration
#

# Where to load database
DATA_PATH = Pathname.new(ENV['DATA_PATH'])
# Where to store data files
OUTPUT_DIR = Pathname.new(ENV['OUTPUT_DIR'])
# Where the database located
DB_FILENAME = DATA_PATH + ENV['DB_FILENAME']
# Current month
DATETIME = Time.new.strftime('%Y-%m')
HEADERS = ['DateTime', 'Logined Users', 'Machine Load'].freeze

#
# Utils function
#

Machine = Struct.new('Machine', :id, :name, :team)
Record = Struct.new('Record', :ttime, :users, :load)

def get_all_machine(db)
  db.execute('SELECT id, name, team FROM machine').collect { |row| Machine.new(row[0], row[1], row[2]) }
end

def get_data(db, machine_id)
  db.query("SELECT ttime, users, load
      FROM record
      WHERE machine=?
      AND DATE(ttime, 'unixepoch')
      BETWEEN
        DATE('now', 'start of month')
      AND
        DATE('now', 'start of month', '+1 month', '-1 day')",
           machine_id)
    .collect { |row| Record.new(Time.at(row[0]), row[1], row[2]) }
end

def p95_by(records, by)
  sorted = records.sort_by do |rec|
    rec[by]
  end
  sorted[(sorted.length * 0.95).ceil - 1][by]
end

def p95_rec(slice)
  cpu_usage = ((p95_by(slice, :load) / 4) * 100).round(3)
  {
    date: slice[0].ttime.iso8601,
    p95Users: p95_by(slice, :users),
    p95Load: cpu_usage
  }
end

def filter_data(records)
  return records if records.length == 1

  result = []
  i = 0
  j = 0

  while j < records.length
    if records[i].ttime.day != records[j].ttime.day
      rec = p95_rec(records[i..j])
      result.push(rec)
      i = j
    end
    j += 1
  end

  result.push(p95_rec(records)) if i.zero?

  result
end

def init_location
  filepath = OUTPUT_DIR.join('location.json')
  file = File.open(filepath, 'r') if File.exist?(filepath)
  return {} if file.nil?

  original = file.read
  file.close
  if original && !original.empty?
    JSON.parse(original)
  else
    {}
  end
end

def save_location(loc)
  filepath = OUTPUT_DIR.join('location.json')
  file = File.open(filepath, 'w+')
  file.write(JSON.generate(loc))
  file.close
end

#
# Main logic
#

db = SQLite3::Database.open(DB_FILENAME)
machines = get_all_machine(db)
location = init_location

machines.each do |m|
  record = get_data(db, m.id)
  dirname = "#{m.name}-#{m.team}"
  prefix = OUTPUT_DIR.join(dirname)
  FileUtils.mkdir_p(prefix)
  filename = "#{DATETIME}.json"
  filepath = prefix.join(filename)

  p95data = filter_data(record)
  p95data = JSON.generate(p95data)
  File.open(filepath, 'w') do |f|
    f.write(p95data)
  end

  map = location[m.name]
  if map
    data = map['data']
    data.push(filename) unless data.include? filename
    map['data'] = data
  else
    location[m.name] = {
      path: dirname,
      data: [filename]
    }
  end

  puts "#{filepath} generated"
end

save_location(location)

puts 'Process done'
